### PR TITLE
Include URL for raw files

### LINKED ISSUE #15: Not being applied on Raw files
This plugin is not being applied on the raw file served by GH.

For example, on this page https://raw.githubusercontent.com/sindresorhus/tab-size-on-github/master/content.css the tab size is still 8.

### PR DESCRIPTION
**Pull request by peduarte**
This PR adds `https://raw.githubusercontent.com/*/*` so this plugin will be executed on pages such as: https://raw.githubusercontent.com/sindresorhus/tab-size-on-github/master/content.css

Closes #15

### CODE REVIEW

**Comment by sindresorhus** [comment]
Did you actually test this? None of the selectors applies to the raw preview HTML.

**Comment by peduarte** [comment]
@sindresorhus 

Ooops my bad, I naively assumed GH would use the same selectors and did not test as I felt pretty confident the script injection would work based on the URL pattern provided.

I'll update this PR with the selector needed for the raw file.

Do you have anything in mind? That page has no class or anything we could use.

I guess the following selector would work, but feels a bit too universal:
```
body > pre
```

Which would basically select a `pre` as long as it is an immediate child of `body`.

**Comment by sindresorhus** [comment]
> Do you have anything in mind?

Not really. That preview is rendered by Chrome, not GitHub, so not sure it even makes sense to handle it.

**Comment by peduarte** [comment]
Actually, that preview is rendered by Github.

If you wanted to see Chrome's rendering of the preview you'd have to go to: `view-source:https://raw.githubusercontent.com/Chorus-bdd/chorus-js/master/src/__mocks__/openWebSocket.js`

As you can see Chrome renders the code in a `table` instead of `pre`.

I feel like `body > pre` would suffice. Otherwise we could be more specific and go for `body > pre:only-child` which would only apply given that `pre` is the only child of `body`.

**Comment by sindresorhus** [comment]
> Actually, that preview is rendered by Github.

No, view source it and you'll see it's just plain text: `view-source:https://raw.githubusercontent.com/sindresorhus/tab-size-on-github/master/content.css`

> If you wanted to see Chrome's rendering of the preview you'd have to go to: view-source:https://raw.githubusercontent.com/Chorus-bdd/chorus-js/master/src/__mocks__/openWebSocket.js

That's the Chrome view source rendering, not text file rendering.

---

This seems to work for overriding the Chrome style too though, so merging.

**Pull request merged**
